"use-strict"
const num1 = 1
const str1 = "hello"
const bool1 = true
const null1 = null
const undef1 = undefined
const sym1 = Symbol("a")
const big1 = 10n
const obj1 = { a: 1 }
const arr1 = [1, 2, 3]
const func1 = function() { return 1 }
const num2 = 2
const str2 = "hi"
const bool2 = false
const null2 = null
const undef2 = undefined
const sym2 = Symbol("b")
const big2 = 11n
const obj2 = { b: 2 }
const arr2 = [4, 5, 6]
const func2 = function() { return 2 }
const num3 = 3
const str3 = "ola"
const bool3 = true
const null3 = null
const undef3 = undefined
const sym3 = Symbol("c")
const big3 = 12n
const obj3 = { c: 3 }
const arr3 = [7, 8, 9]
const func3 = function() { return 3 }
const num4 = 4
const str4 = "norok"
const bool4 = false
const null4 = null
const undef4 = undefined
const sym4 = Symbol("d")
const big4 = 13n
const obj4 = { d: 4 }
const arr4 = [10, 11, 12]
const func4 = function() { return 4 }
const num5 = 5
const str5 = "salut"
const bool5 = true
const null5 = null
const undef5 = undefined
const sym5 = Symbol("e")
const big5 = 14n
const obj5 = { e: 5 }
const arr5 = [13, 14, 15]
const func5 = function() { return 5 }
const num6 = 6
const str6 = "privet"
const bool6 = false
const null6 = null
const undef6 = undefined
const sym6 = Symbol("f")
const big6 = 15n
const obj6 = { f: 6 }
const arr6 = [16, 17, 18]
const func6 = function() { return 6 }
const num7 = 7
const str7 = "nihau"
const bool7 = true
const null7 = null
const undef7 = undefined
const sym7 = Symbol("g")
const big7 = 16n
const obj7 = { g: 7 }
const arr7 = [19, 20, 21]
const func7 = function() { return 7 }
const num8 = 8
const str8 = "ohaiogozeimas"
const bool8 = false
const null8 = null
const undef8 = undefined
const sym8 = Symbol("h")
const big8 = 17n
const obj8 = { h: 8 }
const arr8 = [22, 23, 24]
const func8 = function() { return 8 }
const num9 = 9
const str9 = "namaste"
const bool9 = true
const null9 = null
const undef9 = undefined
const sym9 = Symbol("i")
const big9 = 18n
const obj9 = { i: 9 }
const arr9 = [25, 26, 27]
const func9 = function() { return 9 }
const num10 = 10
const str10 = "bonjur"
const bool10 = false
const null10 = null
const undef10 = undefined
const sym10 = Symbol("j")
const big10 = 19n
const obj10 = { j: 10 }
const arr10 = [28, 29, 30]
const func10 = function() { return 10 }